### ISSUE TITLE
Time Data Does not Match format

### ISSUE THREAD

**Issue by Rwilli5** [mbevand/florida-covid19-line-list-data#5]
Marc, this is great work. Some of the best analysis I have seen for Florida. This issue is likely on my end, but I'm wondering if you can help. I am trying to replicate this and subsequently do this for Miami-Dade County. When I run the predictions file and enter in my path for the FL line list data, I get the following error.

"time data '-f' does not match format '%Y-%m-%d'"

I'm not sure if there is something additional I need to run, but this issue has been persistent for me. I wanted to reach out to you to see if you had a solution or can identify what I am doing incorrectly. 

Warm Regards,
-Roy

**Comment by mbevand** [comment]
The CSV filename must start with "YYYY-MM-DD" Also it seems you are passing the command line option `-f` but there is no such option. So run it like this:

`./forecast_deaths.py 2020-07-01-whatever.csv`
